name: Build And Push Image

on:
  push:
    branches:
      - master
      - "v*"
    paths-ignore:
      - '*.md'
      - 'charts/**'
      - 'config/**'
      - 'docs/**'
      - 'LICENSE'
      - 'OWNERS'
      - 'README.md'

jobs:
  docker-push:
    if: github.repository == 'openyurtio/yurt-dashboard'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: |
          VERSION="ci"
          echo ::set-output name=VERSION::${VERSION}
      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build And Push
        run: |
          make docker-build IMAGE_TAG=${{ steps.get_version.outputs.VERSION }}
          make docker-push IMAGE_TAG=${{ steps.get_version.outputs.VERSION }}