name: Build And Push Image

on:
  push:
    branches:
      - master
      - "v*"
    paths-ignore:
      - '*.md'
      - 'charts/**'
      - 'config/**'
      - 'docs/**'
      - 'LICENSE'
      - 'OWNERS'
      - 'README.md'
  schedule:
    # run at UTC 1:30 every day
    - cron:  '30 1 * * *'
  workflow_dispatch: {}

jobs:
  docker-push:
    if: github.repository == 'openyurtio/yurt-dashboard'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            VERSION=latest
          fi
          echo ::set-output name=VERSION::${VERSION}
      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build And Push
        run: |
          make docker-build IMAGE_TAG=${{ steps.get_version.outputs.VERSION }}
          make docker-push IMAGE_TAG=${{ steps.get_version.outputs.VERSION }}